#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : graphite
Version  : 1.3.11
Release  : 1
URL      : https://github.com/silnrsi/graphite/releases/download/1.3.11/graphite2-1.3.11.tgz
Source0  : https://github.com/silnrsi/graphite/releases/download/1.3.11/graphite2-1.3.11.tgz
Summary  : "Interface to SIL's Graphite2 rendering engine"
Group    : Development/Tools
License  : LGPL-2.1 Perl
Requires: graphite-bin
Requires: graphite-lib
Requires: graphite-license
Requires: graphite-data
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : freetype-dev

%description
*** Linux MonoDevelop build instructions. ***
To run unittests first install the libgraphite2-2.0.0 package and ensure that the fonts Paduak and DejaVuSans are installed.

%package bin
Summary: bin components for the graphite package.
Group: Binaries
Requires: graphite-data
Requires: graphite-license

%description bin
bin components for the graphite package.


%package data
Summary: data components for the graphite package.
Group: Data

%description data
data components for the graphite package.


%package dev
Summary: dev components for the graphite package.
Group: Development
Requires: graphite-lib
Requires: graphite-bin
Requires: graphite-data
Provides: graphite-devel

%description dev
dev components for the graphite package.


%package lib
Summary: lib components for the graphite package.
Group: Libraries
Requires: graphite-data
Requires: graphite-license

%description lib
lib components for the graphite package.


%package license
Summary: license components for the graphite package.
Group: Default

%description license
license components for the graphite package.


%prep
%setup -q -n graphite2-1.3.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533749500
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build ; make test ||: ; popd

%install
export SOURCE_DATE_EPOCH=1533749500
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/graphite
cp COPYING %{buildroot}/usr/share/doc/graphite/COPYING
cp LICENSE %{buildroot}/usr/share/doc/graphite/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gr2fonttest

%files data
%defattr(-,root,root,-)
/usr/share/graphite2/graphite2-relwithdebinfo.cmake
/usr/share/graphite2/graphite2.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/graphite2/Font.h
/usr/include/graphite2/Log.h
/usr/include/graphite2/Segment.h
/usr/include/graphite2/Types.h
/usr/lib64/libgraphite2.so
/usr/lib64/pkgconfig/graphite2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgraphite2.so.3
/usr/lib64/libgraphite2.so.3.0.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/graphite/COPYING
/usr/share/doc/graphite/LICENSE
